config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"

  devise_for :users

  resources :users, only: %i[show], path: 'profile' do
    resources :bookings, only: %i[index edit]
  end

  resources :bookings, only: %i[update destroy]

  resources :vehicules, only: %i[new create edit update destroy]

  resources :vehicules, only: %i[index show] do
    resources :bookings, only: %i[new create]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :vehicule
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true, inclusion: { in: %w[Pending Accepted Declined Passed] }

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :vehicules, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, format: { with: /\A[a-zA-Z\s]+\z/, message: "only allows letters and whitespace" }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z\s]+\z/, message: "only allows letters and whitespace" }
  validates :birthday, presence: true

  after_create :generate_initials_image

  def generate_initials_image

    image = Cloudinary::Uploader.upload("https://via.placeholder.com/150x150.png?text=#{initials}",
      public_id: "user_#{id}_initials",
      transformation: [
        { width: 150, height: 150, gravity: "center", crop: "fill" },
        { overlay: "text:Arial_60_bold:#{initials}", gravity: "center", color: "white" }
      ]
    )

    self.update(image_url: image['secure_url'])
  end

  private

  def initials
    "#{first_name[0].upcase}#{last_name[0].upcase}"
  end

end

app/models/vehicule.rb
class Vehicule < ApplicationRecord
  belongs_to :user

  has_many :bookings, dependent: :destroy

  validates :address, presence: true
  validates :category, presence: true
  validates :brand, presence: true
  validates :model, presence: true
  validates :energy, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..40 }
  validates :color, presence: true, format: { with: /\A[a-zA-Z\s]+\z/, message: "only allows letters and whitespace" }
  validates :year, presence: true, numericality: { only_integer: true }, inclusion: { in: 1900..Date.today.year }
  validates :license_plate, presence: true, format: { with: /\A[A-Z]{2}-[0-9]{3}-[A-Z]{2}\z/, message: "only allows the format XX-000-XX" }
  validates :price_per_h, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..1000 }
  validates :price_per_d, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..10000 }
  validates :description, presence: true, length: { minimum: 50, maximum: 600 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name birthday])

  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user_bookings = Booking.where(user_id: current_user.id)
    @owner_bookings = Booking.where(vehicule: current_user.vehicules)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.vehicule = Vehicule.find(params[:vehicule_id])
    @booking.status = 'Pending'
    if @booking.save
      redirect_to vehicules_path, notice: 'Votre demande de réservation a bien été envoyée'
    else
      render :new, status: :unprocessable_entity, locals: { booking: @booking }
    end
  end

  def edit
    @user = current_user
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(status: params[:status])
    redirect_to user_bookings_path(@booking.user), notice: 'Booking was successfully updated.'
  end

  # def destroy
  #   @booking = Booking.find(params[:id])
  #   @booking.destroy
  #   redirect_to user_bookings_path(@booking.user), notice: 'Booking was successfully canceled.'
  # end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def show
    @user = User.find(params[:id])
    @vehicules = @user.vehicules
  end
end

app/controllers/vehicules_controller.rb
class VehiculesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @vehicules = Vehicule.all
  end

  def show
    @vehicule = Vehicule.find(params[:id])
  end
  def new
    @vehicule = Vehicule.new
  end

  def create
    @vehicule = Vehicule.new(vehicule_params)
    @vehicule.user = current_user
    if @vehicule.save
      redirect_to vehicules_path
    else
      # preserve input values
      render :new, status: :unprocessable_entity, locals: { vehicule: @vehicule }
    end
  end

  def edit
    @vehicule = Vehicule.find(params[:id])

  end

  def destroy
    @vehicule = Vehicule.find(params[:id])
    @vehicule.destroy
    redirect_to user_path(current_user)
  end

  private

  def vehicule_params
    params.require(:vehicule).permit(:address, :category, :brand, :model, :energy, :capacity, :color, :year, :license_plate, :price_per_h, :price_per_d, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(model, url: vehicule_bookings_path) do |f| %>

  <%= f.error_notification  %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<%# , as: :date_picker
, as: :date_picker %>

app/views/bookings/index.html.erb
<h2>Mes réservations</h2>


<% @user_bookings.each do |booking| %>
  <div style="display: flex">
    <p style="margin-left: 15px;"><%= booking.vehicule.brand %>: <%= booking.vehicule.model %></p>
    <p style="margin-left: 15px;">// Du : <%= booking.start_date %> au <%= booking.end_date %></p>
    <p style="margin-left: 15px;">// Prix : <%= (booking.end_date - booking.start_date).to_i * booking.vehicule.price_per_d %>€</p>
    <p style="margin-left: 15px; color: grey"><%= booking.status %></p>
    <% if booking.status == "Pending" && booking.user == current_user %>
      <%= link_to "Refuser", booking_path(booking, status: "Declined"), data: {turbo_confirm: "Voulez-vous vraiment refuser", turbo_method: :patch} %>
      <%= link_to "Accepter", booking_path(booking, status: "Accepted"), data: {turbo_confirm: "Voulez-vous vraiment accepter", turbo_method: :patch} %>
    <% end %>
    <%# link_to for destroy booking %>
    <%# <%= link_to "Annuler", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

<hr>
<h2>Mes demandes de réservation</h2>

<% @owner_bookings.each do |booking| %>

  <div style="display: flex">
    <p style="margin-left: 15px;"><%= booking.vehicule.brand %>: <%= booking.vehicule.model %></p>
    <p style="margin-left: 15px;">// Du : <%= booking.start_date %> au <%= booking.end_date %></p>
    <p style="margin-left: 15px;">// Prix : <%= (booking.end_date - booking.start_date).to_i * booking.vehicule.price_per_d %>€</p>
    <p style="margin-left: 15px; color: grey"><%= booking.status %></p>
    <% if booking.status == "Pending" && booking.user == current_user %>
      <%= link_to "Refuser", booking_path(booking, status: "Declined"), data: {turbo_confirm: "Voulez-vous vraiment refuser", turbo_method: :patch} %>
      <%= link_to "Accepter", booking_path(booking, status: "Accepted"), data: {turbo_confirm: "Voulez-vous vraiment accepter", turbo_method: :patch} %>
    <% end %>
    <%# link_to for destroy booking %>
    <%# <%= link_to "Annuler", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>

<% end %>

app/views/bookings/new.html.erb
<h1>Create new booking</h1>

<%= render 'form', model: @booking %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JackyBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1></strong>Loue la voiture de tes rêves sans te ruiner!</h1>
    <p>Pour un weekend, une journée ou seulement quelques heures.</p>
    <%= link_to "Voir les annonces", vehicules_path, class: "btn-banner"%>
  </div>
</div>
<%# ------------------------------------------------------------------- %>

<div class="cards">
  <div class="card-category", id="car">
    Voitures
  </div>

  <div class="card-category", id="moto">
    Deux-roues
  </div>

  <div class="card-category", id="truck">
    Poids lourds
  </div>
</div>

<%# ------------------------------------------------------------------- %>

app/views/shared/_card_vehicule.html.erb
<div class="card-vehicule">
  <%= image_tag "camion.jpg", class: "card-image" %>
  <div class="card-vehicule-body">
    <h5 class="card-vehicule-title"><%= vehicule.brand %> <%= vehicule.model %></h5>
    <p class="card-vehicule-text"><%= vehicule.capacity %> places</p>
    <p class="card-vehicule-text"><%= vehicule.energy %></p>
    <p class="card-vehicule-text"><strong>A partir de <%= vehicule.price_per_h %>€/h</strong></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-jacky">
  <div class="container-fluid mx-2">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "jacky-logo.png", id: "logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Trouver un véhicule", vehicules_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Déposer une annonce",new_vehicule_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Acceuil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item-dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.image_url, class: "avatar", alt: "dropdown menu" %>
            <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Réservations", user_bookings_path(current_user), class: "dropdown-item" %>
              <%= link_to "Déposer une annonce", new_vehicule_path, class: "dropdown-item" %>
              <%= link_to "Paramètres de compte", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <ul class="navbar-nav me-auto">

          <li class="nav-item">
            <%= link_to "Trouver un véhicule", vehicules_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Déposer une annonce",new_vehicule_path, class: "nav-link" %>
          </li>
          <li class="nav-item" id="btn-login">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>



        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jacky-container">

  <% if @user == current_user %>
    <h1>Mon Profil</h1>
  <% else %>
  <div class="user-info">
    <h2 style="display: inline-block">Profil de <%= @user.first_name %> <%= @user.last_name %></h2>
    <%= image_tag @user.image_url, class: "avatar" %>
  </div>
  <% end %>

  <hr>
  <h3><strong>Mes annonces</strong><h3></h3>

    <% @vehicules.each do |vehicule| %>
      <div class="card-vehicule-owner">
        <%= render 'shared/card_vehicule', vehicule: vehicule %>

          <% if vehicule.user == current_user %>
            <%= button_to edit_vehicule_path(vehicule), method: :get, class: "edit-btn" do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
            <%= button_to vehicule_path(vehicule), method: :get, method: :delete, data: { turbo_confirm: "Êtes-vous sûr de vouloir supprimer ce véhicule ?" },class: "delete-btn" do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          <% end %>

      </div>
    <% end %>

</div>
<%# <i class="fa-solid fa-pen-to-square"></i> %>
<%# <i class="fa-solid fa-trash-can"></i> %>

app/views/vehicules/_btn_booking.html.erb
<% if current_user != vehicule.user %>
  <%= link_to "Réserver", new_vehicule_booking_path(@vehicule), class: "btn-request link_to" %>
<% end %>

<%# use with <%= render "btn_booking", vehicule: @vehicule %>

app/views/vehicules/_form.html.erb
<%= simple_form_for(model) do |f| %>

  <%= f.error_notification  %>

  <div class="form-inputs">
    <%= f.input :address %>
    <%= f.input :category, collection: %w[Voiture Deux-roue Poids-lourd] %>
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :energy %>
    <%= f.input :capacity %>
    <%= f.input :color %>
    <%= f.input :year %>
    <%= f.input :license_plate %>
    <%= f.input :price_per_h %>
    <%= f.input :price_per_d %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vehicules/index.html.erb
<div class="jacky-container">
<h1>Toutes les annonces</h1>


<%= simple_form_for :search, url: vehicules_path, method: :get, local: true do |f| %>
  <div class="filter-bar">
    <%= f.input :category, collection: %w[Categorie Voiture Deux-roue Poids-lourd], selected: "Categorie", label: false, class: "input" %>
    <%= f.input :brand, placeholder: "Marque", label: false, class: "input" %>
    <%= f.input :model, placeholder: "Modèle", label: false, class: "input" %>
    <%= f.input :energy, collection: %w[Carburant Essence Diesel Electrique GPL Hybride], selected: "Energie", label: false, class: "input" %>
    <%= f.input :capacity, placeholder: "Capacité", input_html: { type: 'number' },label: false, class: "input" %>
    <%# <%= f.input :price_min, placeholder: "Prix minimum", label: false, class: "input" %>
    <%# <%= f.input :price_max, placeholder: "Prix maximum", label: false, class: "input" %>
    <%= f.submit "Rechercher", class: "submit-button"%>
  </div>
<% end %>

  <div class="cards px-0">
    <% @vehicules.each do |vehicule| %>
    <%= link_to vehicule_path(vehicule), class: "link_to" do %>
      <%= render 'shared/card_vehicule', vehicule: vehicule %>
    <%end %>
    <% end %>
  </div>
</div>

app/views/vehicules/new.html.erb
<div class="jacky-container">
  <h1>Create new vehicule</h1>
  <%= render 'form', model: @vehicule %>
</div>

app/views/vehicules/show.html.erb
  <div class="jacky-container">
<div class="infos-card">
  <div class ="imgs">
    <div>
      <%= image_tag "moto.jpg",  class: "main-img" %>
    </div>
    <div style="display: flex; flex-direction: column">
      <%= image_tag "voiture", class: "side-imgs" %>
      <%= image_tag "camion", class: "side-imgs" %>
    </div>
  </div>
  <div class="vehicule-title">
    <h2><strong><%= @vehicule.brand %> <%= @vehicule.model %></strong></h2>
  </div>

  <div>
    <p><%= @vehicule.description %></p>
  </div>

  <div class= "infos-container">
    <div class="caracteristics-card">
      <ul>
          <li>Catégorie  <strong><%= @vehicule.category %></strong></li>
          <li>Année  <strong><%= @vehicule.year %></strong></li>
          <li>Couleur  <strong><%= @vehicule.color %></strong></li>
          <li>Energie  <strong><%= @vehicule.energy %></strong></li>
        </ul>
        <div>
          <div class="capacity">
            <i class="fa-solid fa-user"></i>
            <%= @vehicule.capacity %>
          </div>
          </div>
    </div>
    <div class= "owner-card">
      <div class="owner-info">
        <div class= "avatar owner-avatar">
          <%= image_tag @vehicule.user.image_url, class: "avatar", alt: "dropdown menu" %>
        </div>
        <div class="owner">
          <%= @vehicule.user.first_name %>
          <%= @vehicule.user.last_name %>
        </div>
      </div>
      <p>Nombre de véhicules <strong><%= @vehicule.user.vehicules.count %></strong></p>

      <div class="btn-container">
        <%= link_to "Voir le profil", user_path(@vehicule.user), class: "link_to btn-profil"%>
      </div>
    </div>


    </div>


  </div>

    <div class="btn-container">
      <%= render "btn_booking", vehicule: @vehicule %>

    </div>
  </div>

    </div>
</div>